### ISSUE TITLE
lint only when standard is installed as dependency in npm_modules

### ISSUE THREAD

**Issue by capaj** [shinnn/vscode-standard#11]
I work on many JS projects, unfortunately not all of them use standard. It would be tedious for me to switch the global setting in vscode every time I switch from a non standard project to a standard one. Atom standard.js plugin can detect on it's own if the project is using standard or not. Could we have it the same here maybe?

**Comment by shinnn** [comment]
Use workspace setting instead of user setting. https://code.visualstudio.com/docs/customization/userandworkspace
