### ISSUE TITLE
Variable is not defined.

### ISSUE THREAD

**Issue by Kerwood** [shinnn/vscode-standard#12]
I'm having some issues with vscode-standard tagging my global variables as undefined.
I've just switched from Atom to VSCode and the JS Standard plugin works like a charm in Atom.
I add my global variables to the `"standard"` property in my `package.json` as described here. https://standardjs.com/#i-use-a-library-that-pollutes-the-global-namespace-how-do-i-prevent-variable-is-not-defined-errors

But vscode-standard does not recognize them.

**Comment by shinnn** [comment]
PR welcome.

**Comment by Kerwood** [comment]
So its not a bug? Its a missing feature ?
