### ISSUE TITLE
"Path must be a string. Received undefined" error after updating VS Code to version 1.6.0.

### ISSUE THREAD

**Issue by jmdarling** [shinnn/vscode-standard#7]
After updating VS Code to version 1.6.0, with every keypress I get an error popup with the text: "Path must be a string. Received undefined" when using this package.

**Comment by michikuehne** [comment]
Same issue. Therefore I had to disable the extension.

**Comment by rasmuslundberg** [comment]
First of all, thanks for a really good extension @shinnn and the PR here looks good @jmdarling . Please merge it as soon as possible!

**Comment by rasmuslundberg** [comment]
Please push this to the vscode marketplace, or can i upgrade manually somehow?

**Comment by shinnn** [comment]
Published v0.2.0 that includes https://github.com/shinnn/vscode-standard/pull/8 to the marketplace.
